META:
  - '/content/LLaMA-Adapter_replicated/llama_adapter_v2_multimodal7b/dataset/alpaca_gpt4_data.json'
  - '/content/LLaMA-Adapter_replicated/llama_adapter_v2_multimodal7b/dataset/updated_llava_instruct_150k.json'
